//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChienVHShopOnline.Dtos
{
    
    
    public  class NewsCreationDto
    {
        // public int NewsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public IFormFile Image { get; set; }
        public string Content { get; set; }
        // public Nullable<System.DateTime> CreatedDate { get; set; }
        // public Nullable<int> Status { get; set; } 0 -active , 1-deleted
    
    }
}
